version: '2'

services:

  db:
    image: mariadb
    container_name: mariadb
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./mysql/initdb/:/docker-entrypoint-initdb.d 
      - ./mysql/data/:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=maria_db

  php:
    image: php:fpm
    container_name: php-fpm
    restart: always
    volumes:
      - ./www/:/var/www/html
    expose:
      - "9000"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - db
    restart: always
    ports:
      - 8080:80
    volumes:
      - /sessions

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    volumes_from:
      - php
    ports:
      - 80:80